pimcore_data_hub:
    configurations:
        airports:
            general:
                active: true
                type: dataImporterDataObject
                name: airports
                description: ''
                group: ''
                path: null
                modificationDate: 1700517641
                createDate: 1700426258
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: airports/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '1'
                loadingStrategy:
                    type: id
                    settings:
                        dataSourceIndex: '0'
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /import
                locationUpdateStrategy:
                    type: staticPath
                    settings:
                        path: /import
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: '0'
                cleanup:
                    doCleanup: true
                    strategy: delete
            mappingConfig:
                -
                    label: 'id '
                    dataSourceIndex:
                        - '0'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: airportId
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: ident
                    dataSourceIndex:
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: ident
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: type
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: airportType
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: name
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: coordinates
                    dataSourceIndex:
                        - '4'
                        - '5'
                    transformationResultType: geoPoint
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: coordinates
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            type: asGeopoint
                -
                    label: elevation_ft
                    dataSourceIndex:
                        - '6'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: elevationFt
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: continent
                    dataSourceIndex:
                        - '7'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: continent
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: iso_country
                    dataSourceIndex:
                        - '8'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: country
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: iso_region
                    dataSourceIndex:
                        - '9'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: region
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: municipality
                    dataSourceIndex:
                        - '10'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: municipality
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: scheduled_service
                    dataSourceIndex:
                        - '11'
                    transformationResultType: boolean
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: scheduledService
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: boolean
                -
                    label: gps_code
                    dataSourceIndex:
                        - '12'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: gpsCode
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: iata_code
                    dataSourceIndex:
                        - '13'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: iataCode
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: local_code
                    dataSourceIndex:
                        - '14'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: localCode
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: keywords
                    dataSourceIndex:
                        - '17'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: keywords
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: home_link
                    dataSourceIndex:
                        - '15'
                    settings:
                        mode: both
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: homeLink
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                mode: both
                            type: trim
                -
                    label: wikipedia_link
                    dataSourceIndex:
                        - '16'
                    settings:
                        mode: both
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: wikipediaLink
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                mode: both
                            type: trim
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: '19-11-2023 23:32'
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
