pimcore_data_hub:
    configurations:
        frequencyTypeImport:
            general:
                active: true
                type: dataImporterDataObject
                name: frequencyTypeImport
                description: ''
                group: ''
                path: null
                modificationDate: 1700681385
                createDate: 1700679733
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: frequencyTypeImport/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '6'
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: '3'
                        attributeName: code
                        language: ''
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /radio/frequencyType
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: ''
            mappingConfig:
                -
                    label: frequencyType
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
