pimcore_data_hub:
    configurations:
        frequencyImport:
            general:
                active: true
                type: dataImporterDataObject
                name: frequencyImport
                description: ''
                group: ''
                path: null
                modificationDate: 1700685177
                createDate: 1700679733
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: frequencyImport/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '11'
                loadingStrategy:
                    type: id
                    settings:
                        dataSourceIndex: '0'
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /radio
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: ''
            mappingConfig:
                -
                    label: description
                    dataSourceIndex:
                        - '4'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: description
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: frequencyMhz
                    dataSourceIndex:
                        - '5'
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: '7'
                        attributeName: frequencyMhz
                        attributeLanguage: ''
                    transformationResultType: dataObject
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: frequencyMhz
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: '7'
                                attributeName: frequencyMhz
                                attributeLanguage: ''
                            type: loadDataObject
                -
                    label: frequencyType
                    dataSourceIndex:
                        - '3'
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: '6'
                        attributeName: code
                        attributeLanguage: ''
                    transformationResultType: dataObject
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: frequencyType
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: '6'
                                attributeName: code
                                attributeLanguage: ''
                            type: loadDataObject
                -
                    label: id
                    dataSourceIndex:
                        - '0'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: frequencyId
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
