pimcore_data_hub:
    configurations:
        municipalityImport:
            general:
                active: true
                type: dataImporterDataObject
                name: municipalityImport
                description: ''
                group: ''
                path: null
                modificationDate: 1700679189
                createDate: 1700678900
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: municipalityImport/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '10'
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: '10'
                        attributeName: municipality
                        language: ''
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /municipality
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: ''
            mappingConfig:
                -
                    label: municipality
                    dataSourceIndex:
                        - '10'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: municipality
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
