pimcore_data_hub:
    configurations:
        radioFreqImport:
            general:
                type: dataImporterDataObject
                name: radioFreqImport
                description: ''
                group: ''
                active: false
                path: null
                modificationDate: 1700520356
                createDate: 1700520247
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: radioFreqImport/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '2'
                loadingStrategy:
                    type: notLoad
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /import
                locationUpdateStrategy:
                    type: staticPath
                    settings:
                        path: /import
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: ''
            mappingConfig:
                -
                    label: id
                    dataSourceIndex:
                        - '0'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: freqId
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
