pimcore_data_hub:
    configurations:
        runwaySurfaceImport:
            general:
                active: true
                type: dataImporterDataObject
                name: runwaySurfaceImport
                description: ''
                group: ''
                path: null
                modificationDate: 1700677333
                createDate: 1700676858
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: runwaySurfaceImport/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '8'
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: '5'
                        attributeName: Surface
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /runwaySurface
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: '5'
                cleanup:
                    strategy: unpublish
            mappingConfig:
                -
                    label: surface
                    dataSourceIndex:
                        - '5'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Surface
                            language: ''
                            writeIfTargetIsNotEmpty: false
                            writeIfSourceIsEmpty: false
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
