pimcore_data_hub:
    configurations:
        runwaysImport:
            general:
                type: dataImporterDataObject
                name: runwaysImport
                description: ''
                group: ''
                active: false
                path: null
                modificationDate: 1700520230
                createDate: 1700517610
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: runwaysImport/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '3'
                loadingStrategy:
                    type: id
                    settings:
                        dataSourceIndex: '0'
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /import
                locationUpdateStrategy:
                    type: staticPath
                    settings:
                        path: /import
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: '0'
                cleanup:
                    doCleanup: true
                    strategy: delete
            mappingConfig:
                -
                    label: runwayId
                    dataSourceIndex:
                        - '0'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: runwayId
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
