pimcore_data_hub:
    configurations:
        runwaysImport:
            general:
                active: true
                type: dataImporterDataObject
                name: runwaysImport
                description: ''
                group: ''
                path: null
                modificationDate: 1700678343
                createDate: 1700517610
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: runwaysImport/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '3'
                loadingStrategy:
                    type: id
                    settings:
                        dataSourceIndex: '0'
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /runways
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: '0'
                cleanup:
                    strategy: delete
            mappingConfig:
                -
                    label: runwayId
                    dataSourceIndex:
                        - '0'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: runwayId
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'new column'
                    dataSourceIndex:
                        - '5'
                    transformationResultType: dataObject
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: surface
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: '8'
                        attributeName: Surface
                        attributeLanguage: ''
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: '8'
                                attributeName: Surface
                                attributeLanguage: ''
                            type: loadDataObject
                -
                    label: lengthFt
                    dataSourceIndex:
                        - '3'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: lengthFt
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: widthFt
                    dataSourceIndex:
                        - '4'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: widthFt
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: isLighted
                    dataSourceIndex:
                        - '6'
                    transformationResultType: boolean
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: lighted
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: boolean
                -
                    label: isClosed
                    dataSourceIndex:
                        - '7'
                    transformationResultType: boolean
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: closed
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: boolean
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
