pimcore_data_hub:
    configurations:
        todoListImport:
            general:
                type: dataImporterDataObject
                name: todoListImport
                description: ''
                group: ''
                active: false
                path: null
                modificationDate: 1700594782
                createDate: 1700594593
            loaderConfig:
                type: http
                settings:
                    schema: 'https://'
                    url: jsonplaceholder.typicode.com/todos/
            interpreterConfig:
                type: json
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '4'
                loadingStrategy:
                    type: id
                    settings:
                        dataSourceIndex: id
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /todoList/list
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: sequential
                idDataIndex: id
                doDeltaCheck: true
                cleanup:
                    doCleanup: true
                    strategy: delete
            mappingConfig:
                -
                    label: userId
                    dataSourceIndex:
                        - userId
                    transformationResultType: dataObject
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: userId
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: '5'
                        attributeName: userId
                        attributeLanguage: ''
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: '5'
                                attributeName: userId
                                attributeLanguage: ''
                            type: loadDataObject
                -
                    label: id
                    dataSourceIndex:
                        - id
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: listId
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: title
                    dataSourceIndex:
                        - title
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: title
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: completed
                    dataSourceIndex:
                        - completed
                    transformationResultType: boolean
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: completed
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: boolean
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
